### PR TITLE
[redo] (develop ifbyphone) improvements

### PR DESCRIPTION
**Pull request by kares**
there are separate 3+1 branches built upon each other : 
- **[develop-ifbyphone-0-green-base](https://github.com/kares/adhearsion/compare/develop...kares:develop-ifbyphone-0-green-base)** https://travis-ci.org/kares/adhearsion/builds/53029253
- **[develop-ifbyphone-1-no-ruby-spawn](https://github.com/kares/adhearsion/compare/develop-ifbyphone-0-green-base...kares:develop-ifbyphone-1-no-ruby-spawn)** https://travis-ci.org/kares/adhearsion/builds/53032312
- **[develop-ifbyphone-2-tuned-logging](https://github.com/kares/adhearsion/compare/develop-ifbyphone-1-no-ruby-spawn...kares:develop-ifbyphone-2-tuned-logging)** https://travis-ci.org/kares/adhearsion/builds/53033234
- **[develop-ifbyphone-3-fast-call-new](https://github.com/kares/adhearsion/compare/develop-ifbyphone-2-tuned-logging...kares:develop-ifbyphone-3-fast-call-new)** https://travis-ci.org/kares/adhearsion/builds/53043971

### CODE REVIEW

**Comment by benlangfeld** [comment]
no-ruby-spawn and fast-call-new have been merged to upstream Adhearsion. Would you guys be prepared to submit the other changes as pull requests for upstream consideration? I'm sure you don't want to be on a fork forever :)

**Comment by Jared-Prime** [comment]
@kares this looks great :+1: 

@sfgeorge and @runningferret please take a look. Everything is AOK as far as I'm concerned, but I want to make sure you have a change to see the changes before we merge.

**Comment by Jared-Prime** [comment]
@benlangfeld Yes, I agree it would be great to move back to mainline. However, @kares [stated elsewhere](https://github.com/cloudvox/apptastic/pull/372#issuecomment-76516385)

> unfortunately as much as I tested (and it drove me a bit nuts) there's some major slowness introduced in the updated stack - I was unable to figure out in a reasonable time what is causing it, thus I can not recommend a AHN/PB stack upgrade (as the initial call performance is a driving factor)

I think we're in agreement that the performance degradation will prevent us from an upgraded stack until we know and fix the causes. When we do and when the problems are fixed, I'm sure we will contribute the enhancements and return to mainline AHN.

**Comment by benlangfeld** [comment]
@Jared-Prime I'd appreciate it if that was reported upstream in full, including a diff of Gemfile.lock between good and bad states, and a demonstration of what "slowness" means so that we can track it down. It doesn't help anyone to keep such problems to yourselves :)

**Comment by kares** [comment]
@benlangfeld from what we've seen is that in terms of "real" concurrent load AHN/PB stack somehow degraded on JRuby ("real" quoted mostly due thread-backed fibers). due numerous circumstances - such as further degrading on an up-to-date JRuby 1.7.x and no easy way to profile it's hard to tell at this point exactly what is the primary cause but it seems to be related to a few actors/singletons that are used a lot (such as the translator). things tend to queue up there - slowing the whole actor call stack down. 

I'm sure if this is to be resolved the team will not hesitate to report upstream ... I guess current reports would be a little vague for you (or maybe I'm wrong). for now it seems the less actor invocations the better.

**Comment by benlangfeld** [comment]
Even if you don't plan to upgrade Ahn, it would be to your benefit to ensure the Adhearsion community at large is aware of performance regressions on the off-chance that someone fixes it for you, making your path forward in the future clearer should you change your mind. It's also just good open-source citizenship. At the very minimum "hey, 2.5.1 is lots slower than 2.5.0" would be nice to have recorded.

**Comment by Jared-Prime** [comment]
Does https://github.com/adhearsion/adhearsion/issues/526 not encapsulate the issue? or should we report more there?

**Comment by benlangfeld** [comment]
Thanks @Jared-Prime, I hadn't seen that issue. It's a good start. Of course I'd always like more details, but I'll use that and ponder on what we might have changed that is relevant.

**Comment by runningferret** [comment]
I won't pretend like I understand all the nuances here with Celluloid, but it looks pretty reasonable from my very base level understanding of how Celluloid works. The fact that two of these are already merged upstream gives me a bit of confidence too :)

**Comment by Jared-Prime** [comment]
:+1: let's merge

**Comment by Jared-Prime** [comment]
@ajayanty please merge

**Comment by ajayanty** [comment]
This has been merged into cloudvox:develop-ifbyphone

**Pull request merged**
