### PR TITLE
DTPORTAL-16509 attempt to fix race to stop_by_redirect

### PR DESCRIPTION
**Pull request by gfaza**
please let me know if i should be targeting a different branch

### CODE REVIEW

**Comment by gfaza** [comment]
attn @sfgeorge

**Comment by sfgeorge** [comment]
Eek, not sure why build is now failing to bundle install on JRuby 9.2.

This isn't a problem you introduced, but if can you see if it's a problem on upstream adhearsion as well?  If it's happening in both places, see if it's possible to resolve.

FYI, there are 2 packaging related specs that _do_ fail in adhearsion. Those are a bit trickier... So don't expect up get a green build. But if you can get past bundle install, then that's a good win.

**Comment by sfgeorge** [comment]
And target branch looks great, ty man

**Comment by gfaza** [comment]
seems the build failure was momentary - rebuild came back green

**Comment by sfgeorge** [comment]
Looks like build soft-failed on JRuby 9.2 with an unfun issue about not being able to install nio4r:
> checking for unistd.h... RuntimeError: The compiler failed to generate an executable file.
> You have to install development tools first.

...A good to know issue, but completely unrelated to this PR.  Just good to know, we'll knock the nio4r issue out separately later.

**Review by sfgeorge — APPROVED** [review]
@gfaza Looks awesome, thank you so much for crushing this 💪  👍 

Please move to Ready for QA on DEV when appropriate.

**Comment by sfgeorge** [comment]
@mattcar Can you go ahead and merge this for us?  FYI: @rkodali2 

@gfaza After this is merged, please create another PR on the apptastic repo associated with the same JIRA ticket which updates to point to the lastest version of adhearsion @ `cloudvox:dialogtech/support/3.0.0.rc1`.

**Comment by gfaza** [comment]
@sfgeorge, the apptastic PR to point at this new version: https://github.com/cloudvox/apptastic/pull/653

**Pull request merged**
