### PR TITLE
Incorporate upstream changes

### PR DESCRIPTION
**Pull request by sfgeorge**
* Merge ~adhearsion/adhearsion#637~ adhearsion/adhearsion#638 into here
* Point to updated cloudvox/Celluloid support branch

### CODE REVIEW

**Comment by sfgeorge** [comment]
@gfaza Can you review this for me?

**Review by gfaza — APPROVED** [review]
👍

**Comment by sfgeorge** [comment]
@gfaza Sorry, I should have waited to ensure that the build passed.  git URL fixed so that Travis can grab our cloudvox/celluloud.  Can you take another glance?

**Review by gfaza — APPROVED** [review]
👍

**Review by gfaza — COMMENTED** [review]
the overall delta no longer includes that upstream change to 'nio4r < 2.4.0' for the sake of specs.  is that intentional, or an accidental artifact of the git maneuvers here?

nm - i see this is very recently no longer needed

**Comment by sfgeorge** [comment]
@mattcar Can you merge this for us?

**Pull request merged**
